#!/usr/bin/env python3
"""
Worklog helper — called by worklog.sh.
Handles start/end actions for agent punch-clock JSON files.

Schema per worklog-protocol.md:
  agents/{agent}/worklog/{YYYY-MM-DD_HH-MM-SS-mmm}_{agent-slug}.json

Centralized index (append-only JSONL):
  agents/worklogs/index.jsonl
  Each line is a one-line JSON summary appended when `end` is called.
  The index is NEVER truncated or overwritten — only appended.

Distributed tracing (OpenTelemetry-compatible):
  trace_id    — UUID generated by top-level Manager; inherited by all dispatched agents.
  parent_task_id — task_id of the dispatching agent; null for top-level Manager.
"""
import sys
import json
import os
import uuid
from datetime import datetime, timezone


def now_utc():
    return datetime.now(timezone.utc)


def iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def cmd_start(args, mirror_to=None):
    if len(args) < 3:
        print("Usage: worklog.sh start <agent> <model> <summary> [dispatched_by] [trace_id] [parent_task_id]", file=sys.stderr)
        sys.exit(1)

    agent = args[0]           # e.g. "agent-ops/manager"
    model = args[1]           # haiku | sonnet | opus
    input_summary = args[2]   # one-line description
    dispatched_by = args[3] if len(args) > 3 else "manager"

    # Distributed tracing fields (backward compatible — optional)
    raw_trace_id = args[4] if len(args) > 4 else ""
    parent_task_id = args[5] if len(args) > 5 else None

    # Resolve trace_id:
    #   - If provided and non-empty: use it as-is (inherited from Manager)
    #   - If not provided and dispatched_by == "user": auto-generate UUID (top-level Manager)
    #   - Otherwise (dispatched_by == "manager" but not provided): empty string (will be filled by dispatch prompt)
    if raw_trace_id:
        trace_id = raw_trace_id
    elif dispatched_by == "user":
        trace_id = str(uuid.uuid4())
    else:
        trace_id = ""

    # Normalize parent_task_id: treat empty string as None
    if not parent_task_id:
        parent_task_id = None

    # Resolve repo root (scripts/ is one level below root)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)

    # Build worklog directory path
    # agent = "agent-ops/manager" → agents/agent-ops/manager/worklog/
    worklog_dir = os.path.join(repo_root, "agents", *agent.split("/"), "worklog")
    os.makedirs(worklog_dir, exist_ok=True)

    # Generate task_id and filename
    t = now_utc()
    ms = t.microsecond // 1000
    timestamp = t.strftime(f"%Y-%m-%d_%H-%M-%S-{ms:03d}")
    agent_slug = agent.replace("/", "-")
    task_id = f"{timestamp}_{agent_slug}"
    filepath = os.path.join(worklog_dir, f"{task_id}.json")

    data = {
        "agent": agent,
        "task_id": task_id,
        "status": "started",
        "started_at": iso(t),
        "ended_at": None,
        "duration_seconds": None,
        "model": model,
        "dispatched_by": dispatched_by,
        "trace_id": trace_id,
        "parent_task_id": parent_task_id,
        "input_summary": input_summary,
        "output_summary": None,
        "brief": input_summary,
    }

    # If mirror_to is provided, record it in the JSON and write a mirror copy
    if mirror_to:
        data["mirror_path"] = mirror_to
        os.makedirs(mirror_to, exist_ok=True)

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    # Write mirror copy if requested
    if mirror_to:
        mirror_file = os.path.join(mirror_to, f"{task_id}.json")
        with open(mirror_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    # Print filepath so caller can capture: FILE=$(worklog.sh start ...)
    print(filepath, end="")


def cmd_end(args, mirror_to=None):
    if len(args) < 3:
        print("Usage: worklog.sh end <file> <status> <output_summary>", file=sys.stderr)
        sys.exit(1)

    filepath = args[0]
    status = args[1]       # completed | failed
    output_summary = args[2]

    if not os.path.isfile(filepath):
        print(f"Error: worklog file not found: {filepath}", file=sys.stderr)
        sys.exit(1)

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    t = now_utc()
    started = datetime.fromisoformat(data["started_at"].replace("Z", "+00:00"))
    duration = max(0, int((t - started).total_seconds()))

    data["status"] = status
    data["ended_at"] = iso(t)
    data["duration_seconds"] = duration
    data["output_summary"] = output_summary

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    # Update mirror copy if mirror_path is recorded in the worklog JSON
    effective_mirror = data.get("mirror_path") or mirror_to
    if effective_mirror:
        task_id = data.get("task_id", os.path.splitext(os.path.basename(filepath))[0])
        mirror_file = os.path.join(effective_mirror, f"{task_id}.json")
        if os.path.isfile(mirror_file):
            with open(mirror_file, "r", encoding="utf-8") as f:
                mirror_data = json.load(f)
            mirror_data["status"] = status
            mirror_data["ended_at"] = data["ended_at"]
            mirror_data["duration_seconds"] = duration
            mirror_data["output_summary"] = output_summary
            with open(mirror_file, "w", encoding="utf-8") as f:
                json.dump(mirror_data, f, indent=2, ensure_ascii=False)

    # ── Centralized index (append-only JSONL) ────────────────────────────────
    # After writing the individual worklog file, append a one-line summary to
    # agents/worklogs/index.jsonl.  This file is NEVER overwritten — only '>>'
    # so the full history is always preserved.
    # ─────────────────────────────────────────────────────────────────────────
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    index_dir = os.path.join(repo_root, "agents", "worklogs")
    os.makedirs(index_dir, exist_ok=True)
    index_path = os.path.join(index_dir, "index.jsonl")

    index_entry = {
        "agent": data["agent"],
        "task_id": data["task_id"],
        "status": data["status"],
        "duration_seconds": data["duration_seconds"],
        "model": data["model"],
        "started_at": data["started_at"],
        "ended_at": data["ended_at"],
        "trace_id": data.get("trace_id", ""),
        "parent_task_id": data.get("parent_task_id"),
        "input_summary": data["input_summary"],
        "output_summary": data["output_summary"],
    }

    with open(index_path, "a", encoding="utf-8") as idx:
        idx.write(json.dumps(index_entry, ensure_ascii=False) + "\n")


def main():
    if len(sys.argv) < 2:
        print("Usage: worklog.sh start|end ...", file=sys.stderr)
        sys.exit(1)

    # Extract --mirror-to from argv before positional parsing
    mirror_to = None
    argv = sys.argv[:]
    if '--mirror-to' in argv:
        idx = argv.index('--mirror-to')
        mirror_to = argv[idx + 1]
        del argv[idx:idx + 2]

    cmd = argv[1]
    rest = argv[2:]

    if cmd == "start":
        cmd_start(rest, mirror_to=mirror_to)
    elif cmd == "end":
        cmd_end(rest, mirror_to=mirror_to)
    else:
        print(f"Unknown command: {cmd}. Use start or end.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
